version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: adbeacon-postgres
    environment:
      POSTGRES_USER: adbeacon_dev_user
      POSTGRES_PASSWORD: adbeacon1234
      POSTGRES_DB: adbeacon
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adbeacon_dev_user -d adbeacon"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: adbeacon-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  adminer:
    image: adminer:4.8.1
    container_name: adbeacon-adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: pepa-linha

volumes:
  postgres_data:
  redis_data: